### ISSUE TITLE
PandA connect function raises exception off main branch

### ISSUE THREAD

**Issue by jwlodek** [bluesky/ophyd-async#140] opened 2024-03-07 19:44 UTC
After pulling from the main branch today the PandA ophyd object cannot complete the `connect` method.

When we run the code that was working yesterday, we get:

```
In [1]: %run -i panda-flyer.py
/nsls2/users/jwlodek/Workspace/ophyd-async/venv/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
---------------------------------------------------------------------------
NotConnected                              Traceback (most recent call last)
File ~/Workspace/ophyd-async/panda-flyer.py:174
    171         panda3 = PandANSLS2("XF:31ID1-ES{PANDA:3}", name="panda3")
    172     return panda3
--> 174 panda3 = asyncio.run(hello_panda())
    176 print(panda3.__dir__())

File /usr/lib64/python3.9/asyncio/runners.py:44, in run(main, debug)
     42     if debug is not None:
     43         loop.set_debug(debug)
---> 44     return loop.run_until_complete(main)
     45 finally:
     46     try:

File /usr/lib64/python3.9/asyncio/base_events.py:647, in BaseEventLoop.run_until_complete(self, future)
    644 if not future.done():
    645     raise RuntimeError('Event loop stopped before Future completed.')
--> 647 return future.result()

File ~/Workspace/ophyd-async/panda-flyer.py:171, in hello_panda()
    169 async def hello_panda():
    170     async with DeviceCollector():
--> 171         panda3 = PandANSLS2("XF:31ID1-ES{PANDA:3}", name="panda3")
    172     return panda3

File ~/Workspace/ophyd-async/src/ophyd_async/core/device.py:172, in DeviceCollector.__aexit__(self, type, value, traceback)
    170 async def __aexit__(self, type, value, traceback):
    171     self._objects_on_exit = self._caller_locals()
--> 172     await self._on_exit()

File ~/Workspace/ophyd-async/src/ophyd_async/core/device.py:168, in DeviceCollector._on_exit(self)
    166 # Connect to all the devices
    167 if connect_coroutines:
--> 168     await wait_for_connection(**connect_coroutines)

File ~/Workspace/ophyd-async/src/ophyd_async/core/utils.py:99, in wait_for_connection(**coros)
     92             logging.exception(
     93                 f"device `{name}` raised unexpected exception "
     94                 f"{type(result).__name__}",
     95                 exc_info=result,
     96             )
     98 if exceptions:
---> 99     raise NotConnected(exceptions)

NotConnected: 
panda3: NotConnected: pva://XF:31ID1-ES{PANDA:3}PVI
```
which seems like the prefix is missing a `:` character.

But when we add in the colon to the prefix, we get a different error:

```
ERROR:root:device `panda3` raised unexpected exception RemoteError
Traceback (most recent call last):
  File "/nsls2/users/jwlodek/Workspace/ophyd-async/src/ophyd_async/panda/panda.py", line 194, in connect
    await pvi_get(self._prefix + "PVI", timeout=timeout) if not sim else None
  File "/nsls2/users/jwlodek/Workspace/ophyd-async/src/ophyd_async/epics/pvi.py", line 48, in pvi_get
    d: Dict[str, Dict[str, Dict[str, str]]] = await backend.get_value()
  File "/nsls2/users/jwlodek/Workspace/ophyd-async/src/ophyd_async/epics/_backend/_p4p.py", line 302, in get_value
    value = await self.ctxt.get(self.read_pv, request=request)
  File "/nsls2/users/jwlodek/Workspace/ophyd-async/venv/lib64/python3.9/site-packages/p4p/client/asyncio.py", line 140, in get
    return (await self._get_one(name, request=request))
  File "/nsls2/users/jwlodek/Workspace/ophyd-async/venv/lib64/python3.9/site-packages/p4p/client/asyncio.py", line 169, in _get_one
    return (await F)
p4p._p4p.RemoteError: Op Create implied error
---------------------------------------------------------------------------
NotConnected                              Traceback (most recent call last)
File ~/Workspace/ophyd-async/panda-flyer.py:174
    171         panda3 = PandANSLS2("XF:31ID1-ES{PANDA:3}:", name="panda3")
    172     return panda3
--> 174 panda3 = asyncio.run(hello_panda())
    176 print(panda3.__dir__())

File /usr/lib64/python3.9/asyncio/runners.py:44, in run(main, debug)
     42     if debug is not None:
     43         loop.set_debug(debug)
---> 44     return loop.run_until_complete(main)
     45 finally:
     46     try:

File /usr/lib64/python3.9/asyncio/base_events.py:647, in BaseEventLoop.run_until_complete(self, future)
    644 if not future.done():
    645     raise RuntimeError('Event loop stopped before Future completed.')
--> 647 return future.result()

File ~/Workspace/ophyd-async/panda-flyer.py:171, in hello_panda()
    169 async def hello_panda():
    170     async with DeviceCollector():
--> 171         panda3 = PandANSLS2("XF:31ID1-ES{PANDA:3}:", name="panda3")
    172     return panda3

File ~/Workspace/ophyd-async/src/ophyd_async/core/device.py:172, in DeviceCollector.__aexit__(self, type, value, traceback)
    170 async def __aexit__(self, type, value, traceback):
    171     self._objects_on_exit = self._caller_locals()
--> 172     await self._on_exit()

File ~/Workspace/ophyd-async/src/ophyd_async/core/device.py:168, in DeviceCollector._on_exit(self)
    166 # Connect to all the devices
    167 if connect_coroutines:
--> 168     await wait_for_connection(**connect_coroutines)

File ~/Workspace/ophyd-async/src/ophyd_async/core/utils.py:99, in wait_for_connection(**coros)
     92             logging.exception(
     93                 f"device `{name}` raised unexpected exception "
     94                 f"{type(result).__name__}",
     95                 exc_info=result,
     96             )
     98 if exceptions:
---> 99     raise NotConnected(exceptions)

NotConnected: 
panda3: RemoteError: Op Create implied error
```

We believe this was introduced with #43 .

**Comment by mrakitin** [comment] 2024-03-07 19:53
@evalott100, why wasn't #136 merged? Is there another, more proper fix planned?

**Comment by evalott100** [comment] 2024-03-08 13:38
I was going to revert because we forgot to rebase, decided against it. Not because of this.

I'll try and reproduce now!

**Closed** 2024-03-08 14:34 UTC
