### ISSUE TITLE
Document and expose functionality from AD plugins

### ISSUE THREAD

**Issue by DiamondJoseph** [bluesky/ophyd-async#177] opened 2024-04-08 14:20 UTC
To enable the HDFWriter to make use of signals exposed by e.g. the StatsPlugin, the plugins should be documented and their possible fields exposed. This would make using them as ScalarSignals easier

**Comment by callumforrester** [comment] 2024-04-16 09:02
Duplicate of #213

**Closed by callumforrester** 2024-04-16 09:02 UTC
